# Лабораторная работа 1. Работа с библиотекой Numpy

Ф.И.О.: Панчук Павел Александрович

In [2]:
# импортируем необходимые библиотеки и функции
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets

# отключим предупреждения Anaconda
import warnings
warnings.simplefilter('ignore')

# будем отображать графики прямо в jupyter'e в формате svg
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

#увеличим дефолтный размер графиков
from pylab import rcParams
rcParams['figure.figsize'] = 8, 5

**Задание 1.** Создайте одномерный вектор `a` целых значений от $l_1$ до $l_2$ включительно. На его основе вычислите следующие вектора и матрицы (размер вектора равен $n = l_2 - l_1 + 1$):

* одномерный вектор длины $n$, состоящий из элементов `a`, расположенных в обратном порядке;
* одномерный вектор длины $n$, состоящий из значений 0 и 1, в котором значение 1 соотвествует элементам, делящимся на 3 в исходном векторе `a`;
* двумерную матрицу-строку размера 1 на $n$, содержащую элементы вектора `a`;
* двумерную матрицу-столбец размера $n$ на 1, содержащую элементы вектора `a`;
* двумерную матрицу размера $n$ на $n$, содержащую все попарные произведения элементов вектора `a`;
* двумерную матрицу размера $n+2$ на $n+2$, основанную на матрице из предыдущего пункта и дополненную "бордюром" из нулей, окружающим ненулевые значения;
* двумерную матрицу размера $n$ на $n$, содержащую элементы вектора `a` на побочной диагонали;
* двумерную матрицу размера $n$ на 3, содержащую повторяющиеся значения из вектора `a` в её столбцах;
* двумерную матрицу размера 5 на $n$, содержащую повторяющиеся значения из вектора `a` в её строках.

Каждый из пунктов должен выводить на экран соответствующее значение.

In [3]:
import numpy as np

# Задаём значения l1 и l2
l1 = 1
l2 = 5

# Создаём одномерный вектор a
n = l2 - l1 + 1
a = np.arange(l1, l2 + 1)

# 1. Одномерный вектор длины n, состоящий из элементов a в обратном порядке
reversed_a = a[::-1]
print("\n1. Вектор в обратном порядке:", reversed_a)

# 2. Одномерный вектор длины n, состоящий из 0 и 1, где 1 для элементов, делящихся на 3
binary_a = (a % 3 == 0).astype(int)
print("\n2. Вектор с 0 и 1 (1 для элементов, делящихся на 3):", binary_a)

# 3. Двумерная матрица-строка размера 1 на n
matrix_row = a.reshape(1, n)
print("\n3. Матрица-строка (1 x n):\n", matrix_row)

# 4. Двумерная матрица-столбец размера n на 1
matrix_col = a.reshape(n, 1)
print("\n4. Матрица-столбец (n x 1):\n", matrix_col)

# 5. Двумерная матрица размера n на n с попарными произведениями элементов a
pairwise_matrix = np.outer(a, a)
print("\n5. Матрица попарных произведений (n x n):\n", pairwise_matrix)

# 6. Двумерная матрица размера (n+2) x (n+2) с бордюром из нулей
bordered_matrix = np.zeros((n + 2, n + 2), dtype=int)
bordered_matrix[1:-1, 1:-1] = pairwise_matrix
print("\n6. Матрица с бордюром из нулей ((n+2) x (n+2)):\n", bordered_matrix)

# 7. Матрица размера n на n с элементами a на побочной диагонали
anti_diag_matrix = np.zeros((n, n), dtype=int)
np.fill_diagonal(np.fliplr(anti_diag_matrix), a)
print("\n7. Матрица с побочной диагональю (n x n):\n", anti_diag_matrix)

# 8. Матрица размера n на 3 с повторяющимися значениями a в столбцах
matrix_repeated_cols = np.tile(a, (3, 1)).T
print("\n8. Матрица с повторяющимися значениями в столбцах (n x 3):\n", matrix_repeated_cols)

# 9. Матрица размера 5 на n с повторяющимися значениями a в строках
matrix_repeated_rows = np.tile(a, (5, 1))
print("\n9. Матрица с повторяющимися значениями в строках (5 x n):\n", matrix_repeated_rows)



1. Вектор в обратном порядке: [5 4 3 2 1]

2. Вектор с 0 и 1 (1 для элементов, делящихся на 3): [0 0 1 0 0]

3. Матрица-строка (1 x n):
 [[1 2 3 4 5]]

4. Матрица-столбец (n x 1):
 [[1]
 [2]
 [3]
 [4]
 [5]]

5. Матрица попарных произведений (n x n):
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]

6. Матрица с бордюром из нулей ((n+2) x (n+2)):
 [[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  0]
 [ 0  2  4  6  8 10  0]
 [ 0  3  6  9 12 15  0]
 [ 0  4  8 12 16 20  0]
 [ 0  5 10 15 20 25  0]
 [ 0  0  0  0  0  0  0]]

7. Матрица с побочной диагональю (n x n):
 [[0 0 0 0 1]
 [0 0 0 2 0]
 [0 0 3 0 0]
 [0 4 0 0 0]
 [5 0 0 0 0]]

8. Матрица с повторяющимися значениями в столбцах (n x 3):
 [[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]

9. Матрица с повторяющимися значениями в строках (5 x n):
 [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


**Задание 2.** Создайте двумерную матрицу `X` размера $n$ на $m$, содержащую случайные величины, распределенные нормально (по гауссовому распределению) со средним $\mu = 0$ и и среднеквадратичным отклонением $\sigma = 1$. Используйте для этого генератор из модуля `numpy.random`. Сделайте следующее:

* Вычислите двумерную матрицу размера $n$ на $m$, в которой все отрицательные значения заменены на 0;
* Вычислите двумерную матрицу `Y` размера $n$ на $m$, каждый элемент которой вычисляется следующим образом: $y_{ij} = sin(x_{ij}) + cos(x_{ji})$;
* Предложите не менее четырех способов выделения целочисленной части из значений матрицы `X`;
* Вычислите двумерную матрицу размера $n$ на 3, содержащую в первом столбце суммы элементов, во втором столбце средние значения, а в третьем столбце среднеквадратичные отклонения для каждой строки матрицы `X`.

In [ ]:
# ваш код здесь
import numpy as np

# Задаём параметры матрицы
n, m = 4, 5  # Размер матрицы
mu, sigma = 0, 1  # Среднее и стандартное отклонение

# Генерация матрицы X
X = np.random.normal(mu, sigma, (n, m))

# 1. Матрица с заменой отрицательных значений на 0
X_non_negative = np.maximum(X, 0)

# 2. Матрица Y с формулой y_ij = sin(x_ij) + cos(x_ji)
Y = np.sin(X) + np.cos(X.T)

# 3. Четыре способа выделения целочисленной части значений матрицы X
integer_parts = {
    "astype(int)": X.astype(int),
    "floor": np.floor(X).astype(int),
    "ceil": np.ceil(X).astype(int),
    "trunc": np.trunc(X).astype(int),
}

# 4. Матрица с суммой, средним и стандартным отклонением строк
row_stats = np.column_stack((X.sum(axis=1), X.mean(axis=1), X.std(axis=1)))

# Вывод результатов
print("Матрица X:")
print(X)

print("\nМатрица с заменой отрицательных значений на 0:")
print(X_non_negative)

print("\nМатрица Y:")
print(Y)

print("\nЦелочисленные части матрицы X:")
for method, matrix in integer_parts.items():
    print(f"\n{method}:\n{matrix}")

print("\nСтатистики по строкам (сумма, среднее, стандартное отклонение):")
print(row_stats)


**Задание 3.** Постройте вектор размера $n$ элементов, заполненный случайными нормально распределенными числами, распределенными со средним равным $\mu$ и среднеквадратичным отклонением $\sigma$. Постройте гистограмму эмпирического распределения при помощи функции `matplotlib.pyplot.hist`. Приведите аргументы, касающиеся выбора оптимального числа карманов (`bins`) при построении гистограммы.

In [ ]:
# ваш код здесь
import numpy as np
import matplotlib.pyplot as plt

# Задаём параметры
n = 1000  # Размер вектора
mu = 0    # Среднее значение
sigma = 1 # Стандартное отклонение

# Генерация случайных нормально распределённых чисел
data = np.random.normal(mu, sigma, n)

# Построение гистограммы
plt.hist(data, bins='auto', alpha=0.7, color='blue', edgecolor='black')
plt.title("Гистограмма нормального распределения")
plt.xlabel("Значения")
plt.ylabel("Частота")
plt.grid(True)
plt.show()

# Обоснование выбора числа карманов
print("Выбор оптимального числа карманов ('bins') зависит от объёма выборки и распределения данных.")
print("Подход 'auto' автоматически выбирает количество карманов на основе метода Скотта или Фридмана-Дьякониса.")
print("Для более крупных выборок рекомендуется использовать большее число карманов.")


**Задание 4.** Вычислите так называемую случайную матрицу Вигнера $W$ размера $n \times n$. Для этого вычислите случайную матрицу $X$ из нормально распределенных чисел (размера $n$ на $n$, $\mu=0$, $\sigma=1$). Матрица $W$ определяется формулой: $$ \frac {(X + X^T)}{\sqrt{2n}}.$$ Вычислите среднее значение и среднеквадратичное отклонение элементов полученной матрицы $W$. 

In [ ]:
# ваш код здесь
import numpy as np

# Задаём параметры
n = 5  # Размер матрицы

# Генерация случайной матрицы X
X = np.random.normal(0, 1, (n, n))

# Вычисление матрицы Вигнера W
W = (X + X.T) / np.sqrt(2 * n)

# Вычисление среднего значения и стандартного отклонения элементов матрицы W
mean_W = np.mean(W)
std_W = np.std(W)

# Вывод результатов
print("Матрица X:")
print(X)

print("\nМатрица Вигнера W:")
print(W)

print("\nСреднее значение элементов W:", mean_W)
print("Среднеквадратичное отклонение элементов W:", std_W)


**Задание 5.** Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $n \times n$ из стандартного нормального распределения, перемножьте их (обычным матричным умножением) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 25- и 75-процентные квантили? Постройте в виде гистограммы распределение максимальных элементов. Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [ ]:
# ваш код здесь
import numpy as np
import matplotlib.pyplot as plt

# Параметры
n = 5  # Размер матриц
experiments = 1000  # Число экспериментов

# Массив для хранения максимальных элементов
max_elements = []

# Повторяем эксперимент 1000 раз
for _ in range(experiments):
    # Генерация двух матриц из стандартного нормального распределения
    A = np.random.normal(0, 1, (n, n))
    B = np.random.normal(0, 1, (n, n))
    
    # Перемножение матриц
    C = A @ B  # Обычное матричное умножение
    
    # Нахождение максимального элемента
    max_elements.append(C.max())

# Вычисление статистик
mean_max = np.mean(max_elements)
quantile_25 = np.percentile(max_elements, 25)
quantile_75 = np.percentile(max_elements, 75)

# Вывод результатов
print("Среднее значение максимальных элементов:", mean_max)
print("25-й перцентиль:", quantile_25)
print("75-й перцентиль:", quantile_75)

# Построение гистограммы
plt.hist(max_elements, bins='auto', alpha=0.7, color='green', edgecolor='black')
plt.title("Гистограмма максимальных элементов")
plt.xlabel("Максимальный элемент")
plt.ylabel("Частота")
plt.grid(True)
plt.show()


**Задание 6.** Сгенерируйте $n$ чисел из распределения Пуассона с параметром $\lambda$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i. Постройте гистограмму эмпирического распределения. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел a (подобный полученному), и генерирует массив, в котором число i встречается a[i] раз.

**Подсказка:** обратите внимание на функции `np.bincount` и `np.repeat`

In [ ]:
# ваш код здесь
import numpy as np
import matplotlib.pyplot as plt

# Параметры
n = 1000  # Количество чисел
lambda_param = 4  # Параметр λ для распределения Пуассона

# Генерация чисел из распределения Пуассона
poisson_data = np.random.poisson(lambda_param, n)

# Формирование массива, где i-й элемент — это количество чисел, равных i
count_array = np.bincount(poisson_data)

# Построение гистограммы
plt.bar(np.arange(len(count_array)), count_array, color='blue', alpha=0.7, edgecolor='black')
plt.title("Гистограмма эмпирического распределения Пуассона")
plt.xlabel("Число")
plt.ylabel("Частота")
plt.grid(True)
plt.show()

# Функция для генерации массива на основе count_array
def generate_from_counts(a):
    """
    Генерирует массив, в котором число i повторяется a[i] раз.

    Parameters:
    a (numpy.ndarray): Массив, где i-й элемент — количество повторений числа i.

    Returns:
    numpy.ndarray: Сгенерированный массив.
    """
    return np.repeat(np.arange(len(a)), a)

# Генерация массива на основе count_array
generated_array = generate_from_counts(count_array)

# Проверка корректности работы функции
print("Исходный массив частот:", count_array)
print("Восстановленный массив:", generated_array)


**Задание 7.** Напишите функцию `scale(X)`, которая принимает на вход двумерную матрицу произвольного размера и масштабирует каждый ее столбец (вычитает среднее и делит полученные значения на стандартное отклонение, вычисленные для всех элементов данного столбца). Учтите случай деления на нулевое значение (добавьте к стандартному отклонению малую константу порядка $10^{-6}$). Загрузите и перемасштабируйте таблицу с векторами признаков из встроенного набора `"Wine recognition dataset"` [https://scikit-learn.org/stable/datasets/toy_dataset.html#wine-dataset ]

In [ ]:
# ваш код здесь
import numpy as np
from sklearn.datasets import load_wine

# Реализация функции scale
def scale(X):
    """
    Масштабирует каждый столбец матрицы X:
    Вычитает среднее и делит на стандартное отклонение для каждого столбца.
    
    Parameters:
    X (numpy.ndarray): Двумерная матрица.
    
    Returns:
    numpy.ndarray: Масштабированная матрица.
    """
    epsilon = 1e-6  # Малая константа для избежания деления на 0
    mean = X.mean(axis=0)
    std = X.std(axis=0) + epsilon
    return (X - mean) / std

# Загрузка набора данных "Wine recognition dataset"
data = load_wine()
X = data.data  # Матрица признаков
feature_names = data.feature_names  # Названия признаков

# Масштабирование признаков
X_scaled = scale(X)

# Вывод оригинальных и масштабированных данных для проверки
print("Первые 5 строк оригинальной матрицы признаков:")
print(X[:5])

print("\nПервые 5 строк масштабированной матрицы признаков:")
print(X_scaled[:5])

# Проверка среднего и стандартного отклонения для масштабированной матрицы
means_scaled = X_scaled.mean(axis=0)
stds_scaled = X_scaled.std(axis=0)
print("\nСредние значения по столбцам масштабированной матрицы (должны быть близки к 0):")
print(means_scaled)

print("\nСтандартные отклонения по столбцам масштабированной матрицы (должны быть близки к 1):")
print(stds_scaled)


**Задание 8.** Постройте в виде набора `scatter`-графиков различные пары признаков из отнормированных данных предыдущего задания. Обратите внимание, что набор данных `"Wine recognition dataset"` представляет собой словарь. Найдите в нём названия признаков объектов и разметку объектов по меткам классов и используйте их для оформления графиков. Какие из полученных графиков по вашему мнению наиболее информативны? Почему?

In [ ]:
# ваш код здесь
import matplotlib.pyplot as plt
from itertools import combinations

# Загрузка данных "Wine recognition dataset"
data = load_wine()
X_scaled = scale(data.data)  # Масштабированные признаки
feature_names = data.feature_names  # Названия признаков
target = data.target  # Метки классов
target_names = data.target_names  # Названия классов

# Создание пар признаков
pairs = list(combinations(range(len(feature_names)), 2))  # Все комбинации двух признаков

# Построение scatter-графиков для каждой пары
num_pairs = len(pairs)
fig, axes = plt.subplots(nrows=4, ncols=4, figsize=(15, 15))
axes = axes.flatten()

for i, (feat1, feat2) in enumerate(pairs[:16]):  # Берём первые 16 пар для примера
    ax = axes[i]
    for label in np.unique(target):
        ax.scatter(
            X_scaled[target == label, feat1],
            X_scaled[target == label, feat2],
            label=target_names[label],
            alpha=0.7
        )
    ax.set_xlabel(feature_names[feat1])
    ax.set_ylabel(feature_names[feat2])
    ax.legend()
    ax.grid(True)

# Удаление пустых подграфиков, если пар меньше 16
for i in range(len(pairs), len(axes)):
    fig.delaxes(axes[i])

fig.suptitle("Scatter-графики различных пар признаков", fontsize=16)
plt.tight_layout()
plt.show()

# Вывод наиболее информативных пар
print("Некоторые графики могут быть информативными для разделения классов.")
print("Например, пары признаков, где кластеры (группы точек) хорошо разделены.")


**Задание 9.** Реализуйте функцию, вычисляющую коэффициенты линейной регрессии $a_1$ и $a_0$ для зависимости вида $y_i(x)=a_1 x_i + a_0$. Для этого обратитесь к материалу второй лекции курса, где был разобран подобный пример. На вход функция должна принимать два вектора $x$ и $y$. Результат работы должен представлять два значения коэффициентов $a_1$ и $a_0$.

In [ ]:
# ваш код здесь
import numpy as np

def linear_regression(x, y):
    # Количество элементов
    n = len(x)
    
    # Суммы, необходимые для вычисления коэффициентов
    sum_x = np.sum(x)
    sum_y = np.sum(y)
    sum_xy = np.sum(x * y)
    sum_xx = np.sum(x * x)
    
    # Вычисление коэффициента a1
    a1 = (n * sum_xy - sum_x * sum_y) / (n * sum_xx - sum_x**2)
    
    # Вычисление коэффициента a0
    a0 = (sum_y - a1 * sum_x) / n
    
    return a1, a0


**Задание 10.** Примените функцию из предыдущего пункта для предсказания того, как прогрессирует диабет у пациентов из набора данных `"Diabetes dataset"`[https://scikit-learn.org/stable/datasets/toy_dataset.html#diabetes-dataset ] Для этого загрузите этот набор. В качестве $x$ используйте значения признака индекса массы тела (`bmi`), в качестве $y$ - значения по ключу `target`. Вычислите коэффициенты $a_1$ и $a_0$. Постройте график с осью абсцисс, отвечающей за значения `bmi`, осью ординат со значениями `target`. В виде 442 точек нанесите примеры из загруженных данных, в виде прямой представьте предсказания модели. Подпишите оси координат и метки значений на осях

In [ ]:
# ваш код здесь
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes

# Загрузка данных
diabetes_data = load_diabetes()
X = diabetes_data.data[:, 2]  # Индекс массы тела (bmi)
y = diabetes_data.target  # Значения по ключу target

# Применение функции для вычисления коэффициентов линейной регрессии
def linear_regression(x, y):
    n = len(x)
    sum_x = np.sum(x)
    sum_y = np.sum(y)
    sum_xy = np.sum(x * y)
    sum_xx = np.sum(x * x)
    
    a1 = (n * sum_xy - sum_x * sum_y) / (n * sum_xx - sum_x**2)
    a0 = (sum_y - a1 * sum_x) / n
    
    return a1, a0

a1, a0 = linear_regression(X, y)

# Построение графика
plt.scatter(X, y, color='blue', label='Данные', alpha=0.5)
plt.plot(X, a1 * X + a0, color='red', label=f'Прямая регрессии: $y = {a1:.2f}x + {a0:.2f}$')

# Настройка графика
plt.title('Линейная регрессия для прогноза диабета')
plt.xlabel('Индекс массы тела (BMI)')
plt.ylabel('Target (Прогноз прогрессирования диабета)')
plt.legend()
plt.grid(True)
plt.show()
